---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: lightwalletd-tag-pipeline
spec:
  resources:
    - name: source
      type: git
    - name: cloudlog
      type: cloudEvent
    - name: lightwalletd-image
      type: image
  params:
    - name: tagName
  tasks:
    - name: lightwalletd-build-docker-image
      taskRef:
        name: build-docker-image-from-git-source
      resources:
        inputs:
          - name: docker-source
            resource: source
        outputs:
          - name: builtImage
            resource: lightwalletd-image
          - name: notification
            resource: cloudlog